### PR TITLE
Fix #10 - Retribution with Inna's Mantra

### LINKED ISSUE #10: Mantra of Retribution: Transgression APS bonus does not get doubled with Inna's Mantra
This looks like an oversight.

It also needs to be added to the group buffs, because allies gain +20% IAS as well when the support monk is wearing Inna's Mantra.

### PR DESCRIPTION
**Pull request by dominiklohmann**
This changes it so the effect of Mantra of Retribution can actually be
doubled with Inna's Mantra.

### CODE REVIEW

**Comment by d07RiV** [comment]
Thanks, not sure how I missed it :o

**Comment by dominiklohmann** [comment]
Can you double check if that was all places the 2x multiplier was needed in? I'm still unsure where everything is in the codebase... it could use some comments :wink:

**Comment by d07RiV** [comment]
Btw you can't reference box values and other variable factors in a static object, gotta make a callback for that.

**Comment by dominiklohmann** [comment]
> Btw you can't reference box values and other variable factors in a static object, gotta make a callback for that.

Fucking JS, yet again. 

> Yeah generally you only need to fix it in two places (the main calc and the sim), and group buffs if necessary.

I just searched for "mantraofretribution" in the repository - thanks for confirming I got them all.

**Pull request merged**
