### PR TITLE
Sash of Knives affix proc

### PR DESCRIPTION
**Pull request by rubensayshi**
this proc was missing completely, but I'm not sure if this is correct or if it has an internal cooldown or something like that...

asking for info here; http://us.battle.net/d3/en/forum/topic/13272697194?page=2#33 
how do you normally get that info?

sound impossible to me that it wouldn't have an internal cooldown ... ?

and is this the correct way to add the effect? all I need to do is to add `affixes.<match name of the item>`?

### CODE REVIEW

**Comment by dominiklohmann** [comment]
http://ptr.d3planner.com/game/items
> **Unique_Belt_102_p2**
> Name: Sash of Knives
> Power: ItemPassive_Unique_Ring_753_p2

http://ptr.d3planner.com/powers/ItemPassive_Unique_Ring_753_p2
> Target Find Range: 50 
> Proc Chance: 1
> Projectile Speed: 2
> Internal Cooldown: 0.9 / Attacks_Per_Second_Total

`Attacks_Per_Second_Total` is usually your sheet APS, except for a few notable exceptions like Bane of the Stricken.

**Comment by rubensayshi** [comment]
hmm, ok, where is this `/game/items` and `/powers` coming from? some other (private?) repo?

**Comment by dominiklohmann** [comment]
Both are datamined from the game files afaik. There's some other links as well, you might wanna read README.md.

**Comment by rubensayshi** [comment]
Thunderfury and Andariel's Visage also say `Script Formula 4: 0.9 / Attacks_Per_Second_Total`

but their internal cooldown that is in the d3planner code is; `54 / Sim.stats.info.aps`,

what am I missing? or is this a mistake?

**Comment by dominiklohmann** [comment]
1 second = 60 frames
0.9 seconds = 54 frames

**Comment by rubensayshi** [comment]
<3 thanks, updating PR

**Comment by rubensayshi** [comment]
`self: true` means it originates from self not from target right?

**Comment by dominiklohmann** [comment]
I think so, but I am not entirely sure about it. Maybe @d07RiV can have a look at it before he merges it.

**Comment by d07RiV** [comment]
I tried to document the simulator API a while ago here: https://github.com/d07RiV/d3planner/blob/master/simulator/docs.txt  
Some of it is outdated, though; maybe I'll fix it one day.

You didn't quite get the damage data right - you need to specify 'type' unless it is instant damage with known targets (we probably want the projectile speed here so that its not instant).

The data pages were mined from the game, using the code here: https://github.com/d07RiV/SNOParser (I haven't committed it in a while, but I mostly change the main function to call various code to extract data).

**Comment by d07RiV** [comment]
I also added the legacy version just in case. Still not sure if it actually pierces (in which case pierce=true would be needed), and if it depends on the proc coefficient.

**Comment by dominiklohmann** [comment]
It's independent of proc coefficients (but can only proc from attacks with a proc coefficient that is not 0%). The projectile does not pierce.

These mechanics were last tested with 2.3, but I don't think they changed since. The belt has never been "viable", so I never came around to testing it again after that.

**Comment by rubensayshi** [comment]
okay, I thought the `type: line` would mean it would be a line that pierces

thanks for explaining, and I'm gonna take a look at that data mining project because i've always been curious about how it works.

**Comment by d07RiV** [comment]
Okay its a complete mess though :)

The function `dump_data` in `garbage.cpp` is what generates a json with full item/skill data.

**Pull request merged**
